# -*- coding: utf-8 -*-
import os, re
from datetime import datetime
import openpyxl

IMPORT_DIR = r"C:\Users\Пользователь\Desktop\redexpert\_pril_v1\pril2_data\import"
OUT = r"C:\BookStore\module1_setup.sql"

def esc(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''").strip() + "'"

def esc_blob(s):
    if s is None or str(s).strip() == "":
        return "NULL"
    return esc(s)

lines = []
lines.append("-- Module 1: BookStore - run in RDBExpert SQL editor (connected to database.fdb)")
lines.append("SET SQL DIALECT 3;")
lines.append("")

ddl = """
CREATE TABLE role (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE category (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE manufacturer (
  manufacturer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manufacturer_name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE supplier (
  supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INTEGER NOT NULL,
  full_name VARCHAR(200) NOT NULL,
  login VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE product (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article VARCHAR(20) NOT NULL UNIQUE,
  product_name VARCHAR(300) NOT NULL,
  unit_measure VARCHAR(10) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  category_id INTEGER NOT NULL,
  manufacturer_id INTEGER NOT NULL,
  supplier_id INTEGER NOT NULL,
  discount NUMERIC(5,2) DEFAULT 0,
  quantity_stock INTEGER NOT NULL DEFAULT 0,
  description BLOB SUB_TYPE TEXT,
  photo_path VARCHAR(255)
);

CREATE TABLE pickup_point (
  pickup_point_id INTEGER NOT NULL PRIMARY KEY,
  address VARCHAR(300) NOT NULL
);

CREATE TABLE order_status (
  status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE orders (
  order_id INTEGER NOT NULL PRIMARY KEY,
  order_date DATE NOT NULL,
  delivery_date DATE,
  pickup_point_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  pickup_code INTEGER NOT NULL,
  status_id INTEGER NOT NULL
);

CREATE TABLE order_item (
  order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL
);

ALTER TABLE users ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES role(role_id);
ALTER TABLE product ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(category_id);
ALTER TABLE product ADD CONSTRAINT fk_product_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES manufacturer(manufacturer_id);
ALTER TABLE product ADD CONSTRAINT fk_product_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_pickup FOREIGN KEY (pickup_point_id) REFERENCES pickup_point(pickup_point_id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(user_id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_status FOREIGN KEY (status_id) REFERENCES order_status(status_id);
ALTER TABLE order_item ADD CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(order_id);
ALTER TABLE order_item ADD CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES product(product_id);
"""
lines.append(ddl.strip())
lines.append("")

# roles and statuses
lines.append("INSERT INTO role (role_name) VALUES ('Администратор');")
lines.append("INSERT INTO role (role_name) VALUES ('Менеджер');")
lines.append("INSERT INTO role (role_name) VALUES ('Авторизированный клиент');")
lines.append("INSERT INTO order_status (status_name) VALUES ('Завершен');")
lines.append("INSERT INTO order_status (status_name) VALUES ('Новый');")
lines.append("")

# Tovar.xlsx
wb = openpyxl.load_workbook(os.path.join(IMPORT_DIR, "Tovar.xlsx"), read_only=True)
ws = wb.active
rows = list(ws.iter_rows(min_row=2, values_only=True))
wb.close()

cats, mans, sups = {}, {}, {}
for r in rows:
    if not r[0]:
        continue
    cats[r[6]] = None
    mans[r[5]] = None
    sups[r[4]] = None

for name in sorted(cats.keys()):
    lines.append(f"INSERT INTO category (category_name) VALUES ({esc(name)});")
for name in sorted(mans.keys()):
    lines.append(f"INSERT INTO manufacturer (manufacturer_name) VALUES ({esc(name)});")
for name in sorted(sups.keys()):
    lines.append(f"INSERT INTO supplier (supplier_name) VALUES ({esc(name)});")
lines.append("")

for r in rows:
    if not r[0]:
        continue
    art, name, unit, price, sup, man, cat, disc, qty, desc, photo = r
    photo_path = esc(f"import\\{photo}") if photo else "NULL"
    lines.append(
        "INSERT INTO product (article, product_name, unit_measure, price, category_id, manufacturer_id, supplier_id, discount, quantity_stock, description, photo_path) "
        f"SELECT {esc(art)}, {esc(name)}, {esc(unit)}, {price}, "
        f"(SELECT category_id FROM category WHERE category_name={esc(cat)}), "
        f"(SELECT manufacturer_id FROM manufacturer WHERE manufacturer_name={esc(man)}), "
        f"(SELECT supplier_id FROM supplier WHERE supplier_name={esc(sup)}), "
        f"{disc if disc is not None else 0}, {qty if qty is not None else 0}, {esc_blob(desc)}, {photo_path};"
    )
lines.append("")

# pickup points
wb = openpyxl.load_workbook(os.path.join(IMPORT_DIR, "Пункты выдачи_import.xlsx"), read_only=True)
for i, r in enumerate(wb.active.iter_rows(values_only=True), start=1):
    if r[0]:
        lines.append(f"INSERT INTO pickup_point (pickup_point_id, address) VALUES ({i}, {esc(r[0])});")
wb.close()
lines.append("")

# users
wb = openpyxl.load_workbook(os.path.join(IMPORT_DIR, "user_import.xlsx"), read_only=True)
for r in wb.active.iter_rows(min_row=2, values_only=True):
    role, fio, login, pwd = r
    lines.append(
        "INSERT INTO users (role_id, full_name, login, password) "
        f"SELECT (SELECT role_id FROM role WHERE role_name={esc(role)}), {esc(fio)}, {esc(login)}, {esc(pwd)};"
    )
wb.close()
lines.append("")

# orders
def parse_date(v):
    if isinstance(v, datetime):
        return v.strftime("%Y-%m-%d")
    s = str(v).strip()
    if s == "30.02.2024":
        return "2024-02-29"
    for fmt in ("%d.%m.%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(s, fmt).strftime("%Y-%m-%d")
        except ValueError:
            pass
    return "2024-01-01"

def parse_items(s):
    parts = [p.strip() for p in str(s).split(",")]
    pairs = []
    i = 0
    while i < len(parts) - 1:
        pairs.append((parts[i], int(parts[i + 1])))
        i += 2
    return pairs

wb = openpyxl.load_workbook(os.path.join(IMPORT_DIR, "Заказ_import.xlsx"), read_only=True)
for r in wb.active.iter_rows(min_row=2, values_only=True):
    if not r[0]:
        continue
    oid, items, od, dd, pp, fio, code, status = r[:8]
    status = str(status).strip() if status else "Новый"
    if status.startswith("Новый"):
        status = "Новый"
    lines.append(
        "INSERT INTO orders (order_id, order_date, delivery_date, pickup_point_id, user_id, pickup_code, status_id) "
        f"SELECT {int(oid)}, '{parse_date(od)}', '{parse_date(dd)}', {int(pp)}, "
        f"(SELECT user_id FROM users WHERE full_name={esc(fio)}), {int(code)}, "
        f"(SELECT status_id FROM order_status WHERE status_name={esc(status)});"
    )
    for art, qty in parse_items(items):
        lines.append(
            "INSERT INTO order_item (order_id, product_id, quantity) "
            f"SELECT {int(oid)}, (SELECT product_id FROM product WHERE article={esc(art)}), {qty};"
        )
wb.close()

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("Wrote", OUT, "lines", len(lines))
