# -*- coding: utf-8 -*-
from pathlib import Path

fill_path = Path(r"C:\BookStore\module1_fill_data.sql")
full_path = Path(r"C:\BookStore\module1_full.sql")

create = """-- Module 1 full: create schema + insert data
-- Run on a fresh empty database (recommended).

CREATE TABLE ROLE (
  ROLE_ID INTEGER NOT NULL,
  ROLE_NAME VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID),
  CONSTRAINT UQ_ROLE_NAME UNIQUE (ROLE_NAME)
);

CREATE TABLE CATEGORY (
  CATEGORY_ID INTEGER NOT NULL,
  CATEGORY_NAME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);

CREATE TABLE MANUFACTURER (
  MANUFACTURER_ID INTEGER NOT NULL,
  MANUFACTURER_NAME VARCHAR(150) NOT NULL,
  CONSTRAINT PK_MANUFACTURER PRIMARY KEY (MANUFACTURER_ID),
  CONSTRAINT UQ_MANUFACTURER_NAME UNIQUE (MANUFACTURER_NAME)
);

CREATE TABLE SUPPLIER (
  SUPPLIER_ID INTEGER NOT NULL,
  SUPPLIER_NAME VARCHAR(150) NOT NULL,
  CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID),
  CONSTRAINT UQ_SUPPLIER_NAME UNIQUE (SUPPLIER_NAME)
);

CREATE TABLE PICKUP_POINT (
  PICKUP_POINT_ID INTEGER NOT NULL,
  ADDRESS VARCHAR(300) NOT NULL,
  CONSTRAINT PK_PICKUP_POINT PRIMARY KEY (PICKUP_POINT_ID)
);

CREATE TABLE ORDER_STATUS (
  STATUS_ID INTEGER NOT NULL,
  STATUS_NAME VARCHAR(30) NOT NULL,
  CONSTRAINT PK_ORDER_STATUS PRIMARY KEY (STATUS_ID),
  CONSTRAINT UQ_ORDER_STATUS_NAME UNIQUE (STATUS_NAME)
);

CREATE TABLE USERS (
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL,
  FULL_NAME VARCHAR(200) NOT NULL,
  LOGIN VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
  CONSTRAINT UQ_USERS_LOGIN UNIQUE (LOGIN),
  CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

CREATE TABLE PRODUCT (
  PRODUCT_ID INTEGER NOT NULL,
  ARTICLE VARCHAR(20) NOT NULL,
  PRODUCT_NAME VARCHAR(300) NOT NULL,
  UNIT_MEASURE VARCHAR(10) NOT NULL,
  PRICE NUMERIC(10,2) NOT NULL,
  CATEGORY_ID INTEGER NOT NULL,
  MANUFACTURER_ID INTEGER NOT NULL,
  SUPPLIER_ID INTEGER NOT NULL,
  DISCOUNT NUMERIC(5,2) DEFAULT 0,
  QUANTITY_STOCK INTEGER NOT NULL,
  -- Описание из Excel может быть длинным, поэтому храним как текстовый BLOB
  DESCRIPTION BLOB SUB_TYPE TEXT,
  PHOTO_PATH VARCHAR(255),
  CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
  CONSTRAINT UQ_PRODUCT_ARTICLE UNIQUE (ARTICLE),
  CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
  CONSTRAINT FK_PRODUCT_MANUFACTURER FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER(MANUFACTURER_ID),
  CONSTRAINT FK_PRODUCT_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
);

CREATE TABLE ORDERS (
  ORDER_ID INTEGER NOT NULL,
  ORDER_DATE DATE NOT NULL,
  DELIVERY_DATE DATE,
  PICKUP_POINT_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  PICKUP_CODE INTEGER NOT NULL,
  STATUS_ID INTEGER NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_ORDERS_PICKUP_POINT FOREIGN KEY (PICKUP_POINT_ID) REFERENCES PICKUP_POINT(PICKUP_POINT_ID),
  CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
  CONSTRAINT FK_ORDERS_STATUS FOREIGN KEY (STATUS_ID) REFERENCES ORDER_STATUS(STATUS_ID)
);

CREATE TABLE ORDER_ITEM (
  ORDER_ITEM_ID INTEGER NOT NULL,
  ORDER_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL,
  CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ORDER_ITEM_ID),
  CONSTRAINT FK_ORDER_ITEM_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
"""

fill_sql = fill_path.read_text(encoding="utf-8")
full_path.write_text(create + "\n" + fill_sql + "\n", encoding="utf-8")

print("Wrote:", full_path)

